import React, { createContext, useContext, useState } from "react";

export type Language = "pt" | "en";

const translations = {
  pt: {
    // Nav
    nav_home: "Início",
    nav_bank: "Banco de Questões",
    nav_exam: "Simulados",
    nav_leaderboard: "Ranking",
    nav_profile: "Perfil",
    nav_admin: "Admin",
    nav_login: "Entrar",
    nav_logout: "Sair",
    nav_pricing: "Planos",
    // Hero
    hero_badge: "Plataforma #1 para Veterinários",
    hero_title: "Domine a Medicina Veterinária",
    hero_subtitle: "Estude com questões de alta qualidade, compete com colegas e suba de nível com nossa plataforma gamificada.",
    hero_cta_primary: "Começar Grátis",
    hero_cta_secondary: "Ver Planos",
    hero_trial: "30 dias premium grátis • Sem cartão de crédito",
    // Features
    features_title: "Tudo que você precisa para passar",
    features_subtitle: "Uma plataforma completa para sua preparação em medicina veterinária",
    feat_bank_title: "Banco de Questões",
    feat_bank_desc: "5.661 questões em 6 grandes áreas do currículo veterinário, organizadas por assunto e dificuldade",
    feat_exam_title: "Simulados Configuráveis",
    feat_exam_desc: "Monte seu simulado ideal com timer, navegação e correção automática",
    feat_gamification_title: "Gamificação Completa",
    feat_gamification_desc: "XP, níveis, badges e sequências de dias para manter sua motivação",
    feat_ranking_title: "Ranking Competitivo",
    feat_ranking_desc: "Compare seu desempenho com outros estudantes semanalmente",
    feat_ai_title: "IA Explicativa",
    feat_ai_desc: "Explicações detalhadas geradas por IA para cada questão",
    feat_bilingual_title: "Bilíngue PT/EN",
    feat_bilingual_desc: "Estude em português ou inglês conforme sua preferência",
    // Disciplines
    disciplines_title: "Disciplinas Disponíveis",
    disciplines_subtitle: "Cobertura completa das principais áreas da medicina veterinária",
    // Levels
    levels_title: "Sua Jornada de Evolução",
    levels_subtitle: "9 níveis de progressão do Residente à Lenda",
    // Pricing
    pricing_title: "Planos e Preços",
    pricing_subtitle: "Escolha o plano ideal para sua preparação",
    plan_free: "Gratuito",
    plan_trial: "Trial Premium",
    plan_premium: "Premium Anual",
    plan_free_price: "R$ 0",
    plan_trial_price: "R$ 0",
    plan_premium_price: "R$ 299",
    plan_monthly_price: "R$ 39,90",
    plan_per_year: "/ano",
    plan_per_month: "/mês",
    plan_monthly_equiv: "≈ R$24,90/mês",
    plan_discount: "37% OFF",
    plan_free_desc: "Para começar sua jornada",
    plan_trial_desc: "30 dias de acesso total, sem cartão",
    plan_premium_desc: "Melhor custo-benefício — economize R$179,80",
    plan_free_features: ["30 questões por mês", "Banco de questões com filtros", "Ranking geral", "Perfil gamificado básico"],
    plan_trial_features: ["Questões ilimitadas", "Simulados ilimitados", "Ranking completo", "Explicações por IA", "Todos os badges", "30 dias grátis"],
    plan_premium_features: ["Questões ilimitadas", "Simulados ilimitados", "Ranking completo", "Explicações por IA", "Todos os badges", "Suporte prioritário", "37% de desconto vs. mensal"],
    plan_monthly: "Premium Mensal",
    plan_monthly_desc: "Flexibilidade total, cancele quando quiser",
    plan_cta_free: "Começar Grátis",
    plan_cta_trial: "Ativar Trial Grátis",
    plan_cta_monthly: "Iniciar Trial Grátis",
    plan_cta_premium: "Assinar Premium Anual",
    plan_no_card: "Sem cartão de crédito",
    plan_popular: "Melhor Custo-Benefício",
    // Stats
    stats_questions: "Questões",
    stats_students: "Estudantes",
    stats_exams: "Simulados",
    stats_accuracy: "Taxa de Acerto",
    // Exam
    exam_title: "Configurar Simulado",
    exam_discipline: "Disciplina",
    exam_all_disciplines: "Todas as disciplinas",
    exam_difficulty: "Dificuldade",
    exam_all_difficulties: "Todas as dificuldades",
    exam_easy: "Fácil",
    exam_medium: "Médio",
    exam_hard: "Difícil",
    exam_mixed: "Misto",
    exam_count: "Número de Questões",
    exam_timer: "Tempo Limite (minutos)",
    exam_no_timer: "Sem limite de tempo",
    exam_start: "Iniciar Simulado",
    exam_question: "Questão",
    exam_of: "de",
    exam_submit: "Finalizar Simulado",
    exam_next: "Próxima",
    exam_prev: "Anterior",
    exam_time_left: "Tempo restante",
    exam_confirm_submit: "Tem certeza que deseja finalizar?",
    exam_unanswered: "questões sem resposta",
    exam_results_title: "Resultado do Simulado",
    exam_score: "Pontuação",
    exam_correct: "Corretas",
    exam_wrong: "Erradas",
    exam_accuracy: "Taxa de Acerto",
    exam_xp_earned: "XP Ganho",
    exam_time_spent: "Tempo Gasto",
    exam_review: "Revisar Questões",
    exam_new: "Novo Simulado",
    exam_explain_ai: "Explicar com IA",
    exam_your_answer: "Sua resposta",
    exam_correct_answer: "Resposta correta",
    // Question Bank
    bank_title: "Banco de Questões",
    bank_search: "Buscar questões...",
    bank_filter_discipline: "Disciplina",
    bank_filter_subject: "Assunto",
    bank_filter_difficulty: "Dificuldade",
    bank_filter_year: "Ano",
    bank_all: "Todos",
    bank_results: "questões encontradas",
    bank_premium_badge: "Premium",
    bank_no_results: "Nenhuma questão encontrada",
    // Profile
    profile_title: "Meu Perfil",
    profile_level: "Nível",
    profile_xp: "XP Total",
    profile_streak: "Sequência",
    profile_days: "dias",
    profile_accuracy: "Taxa de Acerto",
    profile_exams: "Simulados",
    profile_questions: "Questões",
    profile_badges: "Conquistas",
    profile_history: "Histórico de Simulados",
    profile_no_exams: "Nenhum simulado realizado ainda",
    profile_plan: "Plano",
    profile_trial_ends: "Trial expira em",
    // Leaderboard
    lb_title: "Ranking",
    lb_weekly: "Semanal",
    lb_monthly: "Mensal",
    lb_alltime: "Geral",
    lb_rank: "Posição",
    lb_player: "Jogador",
    lb_xp: "XP",
    lb_level: "Nível",
    lb_empty: "Nenhum dado disponível",
    lb_you: "Você",
    // Admin
    admin_title: "Painel Administrativo",
    admin_questions: "Questões",
    admin_disciplines: "Disciplinas",
    admin_subjects: "Assuntos",
    admin_stats: "Estatísticas",
    admin_add: "Adicionar",
    admin_edit: "Editar",
    admin_delete: "Excluir",
    admin_save: "Salvar",
    admin_cancel: "Cancelar",
    admin_import: "Importar CSV",
    admin_import_desc: "Importe questões em lote via arquivo CSV",
    admin_seed: "Inicializar Dados",
    admin_generate_ai: "Gerar com IA",
    // Common
    loading: "Carregando...",
    error: "Ocorreu um erro",
    retry: "Tentar novamente",
    save: "Salvar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    delete: "Excluir",
    edit: "Editar",
    add: "Adicionar",
    search: "Buscar",
    filter: "Filtrar",
    clear: "Limpar",
    back: "Voltar",
    next: "Próximo",
    prev: "Anterior",
    yes: "Sim",
    no: "Não",
    login_required: "Faça login para continuar",
    login_btn: "Fazer Login",
    // Levels
    level_1: "Residente",
    level_2: "Estagiário",
    level_3: "Clínico Geral",
    level_4: "Especialista",
    level_5: "Consultor",
    level_6: "Pesquisador",
    level_7: "Professor",
    level_8: "Mestre",
    level_9: "Lenda",
  },
  en: {
    nav_home: "Home",
    nav_bank: "Question Bank",
    nav_exam: "Mock Exams",
    nav_leaderboard: "Leaderboard",
    nav_profile: "Profile",
    nav_admin: "Admin",
    nav_login: "Login",
    nav_logout: "Logout",
    nav_pricing: "Pricing",
    hero_badge: "Platform #1 for Veterinarians",
    hero_title: "Master Veterinary Medicine",
    hero_subtitle: "Study with high-quality questions, compete with peers, and level up with our gamified platform.",
    hero_cta_primary: "Start for Free",
    hero_cta_secondary: "View Plans",
    hero_trial: "30-day premium free • No credit card required",
    features_title: "Everything you need to pass",
    features_subtitle: "A complete platform for your veterinary medicine preparation",
    feat_bank_title: "Question Bank",
    feat_bank_desc: "5,661 questions across 6 major veterinary curriculum areas, organized by subject and difficulty",
    feat_exam_title: "Configurable Mock Exams",
    feat_exam_desc: "Build your ideal exam with timer, navigation, and auto-correction",
    feat_gamification_title: "Full Gamification",
    feat_gamification_desc: "XP, levels, badges, and streaks to keep you motivated",
    feat_ranking_title: "Competitive Ranking",
    feat_ranking_desc: "Compare your performance with other students weekly",
    feat_ai_title: "AI Explanations",
    feat_ai_desc: "Detailed AI-generated explanations for every question",
    feat_bilingual_title: "Bilingual PT/EN",
    feat_bilingual_desc: "Study in Portuguese or English as you prefer",
    disciplines_title: "Available Disciplines",
    disciplines_subtitle: "Full coverage of key veterinary medicine areas",
    levels_title: "Your Evolution Journey",
    levels_subtitle: "9 progression levels from Resident to Legend",
    pricing_title: "Plans & Pricing",
    pricing_subtitle: "Choose the ideal plan for your preparation",
    plan_free: "Free",
    plan_trial: "Premium Trial",
    plan_premium: "Annual Premium",
    plan_free_price: "R$0",
    plan_trial_price: "R$0",
    plan_premium_price: "R$299",
    plan_monthly_price: "R$39.90",
    plan_per_year: "/year",
    plan_per_month: "/month",
    plan_monthly_equiv: "≈ R$24.90/month",
    plan_discount: "37% OFF",
    plan_free_desc: "To start your journey",
    plan_trial_desc: "30 days full access, no card",
    plan_premium_desc: "Best value — save R$179.80",
    plan_free_features: ["30 questions/month", "Question bank with filters", "General ranking", "Basic gamified profile"],
    plan_trial_features: ["Unlimited questions", "Unlimited exams", "Full ranking", "AI explanations", "All badges", "30 days free"],
    plan_premium_features: ["Unlimited questions", "Unlimited exams", "Full ranking", "AI explanations", "All badges", "Priority support", "37% off vs. monthly"],
    plan_monthly: "Premium Monthly",
    plan_monthly_desc: "Full flexibility, cancel anytime",
    plan_cta_free: "Start Free",
    plan_cta_trial: "Activate Free Trial",
    plan_cta_monthly: "Start Free Trial",
    plan_cta_premium: "Subscribe Annual Premium",
    plan_no_card: "No credit card required",
    plan_popular: "Best Value",
    stats_questions: "Questions",
    stats_students: "Students",
    stats_exams: "Exams",
    stats_accuracy: "Accuracy Rate",
    exam_title: "Configure Mock Exam",
    exam_discipline: "Discipline",
    exam_all_disciplines: "All disciplines",
    exam_difficulty: "Difficulty",
    exam_all_difficulties: "All difficulties",
    exam_easy: "Easy",
    exam_medium: "Medium",
    exam_hard: "Hard",
    exam_mixed: "Mixed",
    exam_count: "Number of Questions",
    exam_timer: "Time Limit (minutes)",
    exam_no_timer: "No time limit",
    exam_start: "Start Exam",
    exam_question: "Question",
    exam_of: "of",
    exam_submit: "Finish Exam",
    exam_next: "Next",
    exam_prev: "Previous",
    exam_time_left: "Time remaining",
    exam_confirm_submit: "Are you sure you want to finish?",
    exam_unanswered: "unanswered questions",
    exam_results_title: "Exam Results",
    exam_score: "Score",
    exam_correct: "Correct",
    exam_wrong: "Wrong",
    exam_accuracy: "Accuracy",
    exam_xp_earned: "XP Earned",
    exam_time_spent: "Time Spent",
    exam_review: "Review Questions",
    exam_new: "New Exam",
    exam_explain_ai: "Explain with AI",
    exam_your_answer: "Your answer",
    exam_correct_answer: "Correct answer",
    bank_title: "Question Bank",
    bank_search: "Search questions...",
    bank_filter_discipline: "Discipline",
    bank_filter_subject: "Subject",
    bank_filter_difficulty: "Difficulty",
    bank_filter_year: "Year",
    bank_all: "All",
    bank_results: "questions found",
    bank_premium_badge: "Premium",
    bank_no_results: "No questions found",
    profile_title: "My Profile",
    profile_level: "Level",
    profile_xp: "Total XP",
    profile_streak: "Streak",
    profile_days: "days",
    profile_accuracy: "Accuracy",
    profile_exams: "Exams",
    profile_questions: "Questions",
    profile_badges: "Achievements",
    profile_history: "Exam History",
    profile_no_exams: "No exams taken yet",
    profile_plan: "Plan",
    profile_trial_ends: "Trial expires in",
    lb_title: "Leaderboard",
    lb_weekly: "Weekly",
    lb_monthly: "Monthly",
    lb_alltime: "All Time",
    lb_rank: "Rank",
    lb_player: "Player",
    lb_xp: "XP",
    lb_level: "Level",
    lb_empty: "No data available",
    lb_you: "You",
    admin_title: "Admin Panel",
    admin_questions: "Questions",
    admin_disciplines: "Disciplines",
    admin_subjects: "Subjects",
    admin_stats: "Statistics",
    admin_add: "Add",
    admin_edit: "Edit",
    admin_delete: "Delete",
    admin_save: "Save",
    admin_cancel: "Cancel",
    admin_import: "Import CSV",
    admin_import_desc: "Bulk import questions via CSV file",
    admin_seed: "Initialize Data",
    admin_generate_ai: "Generate with AI",
    loading: "Loading...",
    error: "An error occurred",
    retry: "Try again",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    filter: "Filter",
    clear: "Clear",
    back: "Back",
    next: "Next",
    prev: "Previous",
    yes: "Yes",
    no: "No",
    login_required: "Please login to continue",
    login_btn: "Login",
    level_1: "Resident",
    level_2: "Intern",
    level_3: "General Practitioner",
    level_4: "Specialist",
    level_5: "Consultant",
    level_6: "Researcher",
    level_7: "Professor",
    level_8: "Master",
    level_9: "Legend",
  },
};

type TranslationKey = keyof typeof translations.pt;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: TranslationKey) => string | string[];
}

const LanguageContext = createContext<LanguageContextType>({
  language: "pt",
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    return (localStorage.getItem("vetrank_lang") as Language) || "pt";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("vetrank_lang", lang);
  };

  const t = (key: TranslationKey): string | string[] => {
    const val = translations[language][key];
    return val ?? key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export function useT() {
  const { t } = useLanguage();
  return (key: TranslationKey) => t(key) as string;
}
